# Generated by Django 2.2.5 on 2019-11-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191001_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.URLField(default=True, max_length=1000),
        ),
    ]
